# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Sie macht die gRPC-API in Python nutzbar (Client + Server-Verbindung).
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import invoice_pb2 as invoice__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in invoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RechnungsServiceStub(object):
    """gRPC-Dienst: Speichert und liefert Rechnungsmetadaten
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeichereRechnungsmetadaten = channel.unary_unary(
                '/rechnung.RechnungsService/SpeichereRechnungsmetadaten',
                request_serializer=invoice__pb2.Rechnungsmetadaten.SerializeToString,
                response_deserializer=invoice__pb2.SpeicherAntwort.FromString,
                _registered_method=True)
        self.HoleRechnungsmetadaten = channel.unary_unary(
                '/rechnung.RechnungsService/HoleRechnungsmetadaten',
                request_serializer=invoice__pb2.RechnungsAnfrage.SerializeToString,
                response_deserializer=invoice__pb2.Rechnungsmetadaten.FromString,
                _registered_method=True)


class RechnungsServiceServicer(object):
    """gRPC-Dienst: Speichert und liefert Rechnungsmetadaten
    """

    def SpeichereRechnungsmetadaten(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HoleRechnungsmetadaten(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RechnungsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeichereRechnungsmetadaten': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeichereRechnungsmetadaten,
                    request_deserializer=invoice__pb2.Rechnungsmetadaten.FromString,
                    response_serializer=invoice__pb2.SpeicherAntwort.SerializeToString,
            ),
            'HoleRechnungsmetadaten': grpc.unary_unary_rpc_method_handler(
                    servicer.HoleRechnungsmetadaten,
                    request_deserializer=invoice__pb2.RechnungsAnfrage.FromString,
                    response_serializer=invoice__pb2.Rechnungsmetadaten.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rechnung.RechnungsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rechnung.RechnungsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RechnungsService(object):
    """gRPC-Dienst: Speichert und liefert Rechnungsmetadaten
    """

    @staticmethod
    def SpeichereRechnungsmetadaten(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rechnung.RechnungsService/SpeichereRechnungsmetadaten',
            invoice__pb2.Rechnungsmetadaten.SerializeToString,
            invoice__pb2.SpeicherAntwort.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HoleRechnungsmetadaten(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rechnung.RechnungsService/HoleRechnungsmetadaten',
            invoice__pb2.RechnungsAnfrage.SerializeToString,
            invoice__pb2.Rechnungsmetadaten.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
