# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\x12\x08rechnung\"\xb2\x02\n\x12Rechnungsmetadaten\x12\x11\n\tinvoiceId\x18\x01 \x01(\t\x12\x12\n\nsupplierId\x18\x02 \x01(\t\x12\x14\n\x0csupplierName\x18\x03 \x01(\t\x12\x13\n\x0binvoiceDate\x18\x04 \x01(\t\x12\x0f\n\x07\x64ueDate\x18\x05 \x01(\t\x12\x11\n\tamountNet\x18\x06 \x01(\x01\x12\x13\n\x0b\x61mountGross\x18\x07 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x0c\n\x04iban\x18\t \x01(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x10\n\x08\x66ileName\x18\x0b \x01(\t\x12\x11\n\tcreatedAt\x18\x0c \x01(\t\x12\x16\n\x0e\x62illingAddress\x18\r \x01(\t\x12$\n\x05items\x18\x0e \x03(\x0b\x32\x15.rechnung.InvoiceItem\"[\n\x0bInvoiceItem\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x11\n\tunitPrice\x18\x03 \x01(\x01\x12\x12\n\ntotalPrice\x18\x04 \x01(\x01\"F\n\x0fSpeicherAntwort\x12\x11\n\tinvoiceId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x10RechnungsAnfrage\x12\x11\n\tinvoiceId\x18\x01 \x01(\t2\xbe\x01\n\x10RechnungsService\x12V\n\x1bSpeichereRechnungsmetadaten\x12\x1c.rechnung.Rechnungsmetadaten\x1a\x19.rechnung.SpeicherAntwort\x12R\n\x16HoleRechnungsmetadaten\x12\x1a.rechnung.RechnungsAnfrage\x1a\x1c.rechnung.Rechnungsmetadatenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECHNUNGSMETADATEN']._serialized_start=28
  _globals['_RECHNUNGSMETADATEN']._serialized_end=334
  _globals['_INVOICEITEM']._serialized_start=336
  _globals['_INVOICEITEM']._serialized_end=427
  _globals['_SPEICHERANTWORT']._serialized_start=429
  _globals['_SPEICHERANTWORT']._serialized_end=499
  _globals['_RECHNUNGSANFRAGE']._serialized_start=501
  _globals['_RECHNUNGSANFRAGE']._serialized_end=538
  _globals['_RECHNUNGSSERVICE']._serialized_start=541
  _globals['_RECHNUNGSSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
